# Big thanks to this article https://goo.gl/7f3Xdr

version : "1"

services :

	backend-wasabi : # How I chose to name my service
		container_name : backend-wasabi # How i chose to name the container, makes it easier to work with it
		restart : always # If it fails restart it automatically
		build: . # With the Dockerfile in this folder
		ports :
			- "5001:5001" # Mapping host and container ports
		links :
			- mongo # It's going to use "mongo" service, just beneath

	mongo :
		container_name : mongo
		image : mongo # Name of the image in the Docker Hub Registry
		volumes :
			- ./database:/data/db # Map my database located in ./database with the mounting point of the volume in mongo Dockerfile, this way we use a persistant storage, this way it "will use volume of any previous containers and copy it to the new container, ensuring that no data is lost."
		ports :
			- "27017:27017"