# Big thanks to this article https://goo.gl/7f3Xdr

version : "3.6"

services :

    backend-wasabi : # How I chose to name my service
        container_name : backend-wasabi # How i chose to name the container, makes it easier to work with it
        restart : unless-stopped # Stop only if a stop signal is sent to the container
        build : . # With the Dockerfile in this folder
        command : npm run deploy
        ports :
            - "5001:5001" # Mapping host and container ports
        depends_on :
            - "mongo" # It's going to use "mongo" service, just beneath
        links :
            - "mongo"

    mongo :
        container_name : mongodb
        image : "mongo" # Name of the image in the Docker Hub Registry
        restart : unless-stopped
        volumes :
            - mongo-data:/data/db
        env_file :
            ./environments/mongo.env
        expose :
            - "27017"

    admin-mongo :
        container_name : admin-mongo
        restart : unless-stopped
        build : ./adminMongo/
        ports :
            - "1234:1234"
        depends_on :
            - "mongo"
        links :
            - "mongo"

volumes :
    mongo-data: