# Big thanks to this article https://goo.gl/7f3Xdr

version : "3.6"

services :

    backend-wasabi : # How I chose to name my service
        container_name : backend-wasabi # How i chose to name the container, makes it easier to work with it
        restart : unless-stopped # Stop only if a stop signal is sent to the container
        build : . # With the Dockerfile in this folder
        command : npm run deploy
        ports :
            - "5001:5001" # Mapping host and container ports
        depends_on :
            - "mongo" # It's going to use "mongo" service, just beneath
        links :
            - "mongo"

    mongo :
        container_name : mongo-db
        image : "mongo" # Name of the image in the Docker Hub Registry
        restart : unless-stopped
        volumes :
            - mongo-data:/data/db
        env_file :
            ./environments/mongo.env
        expose :
            - "27017"

    adminmongo :
        container_name : admin-mongo
        image : "mrvautin/adminmongo"
        env_file :
            - ./environments/adminMongo.env
        restart : unless-stopped
        depends_on :
            - "mongo"
        links :
            - "mongo"
        ports :
            - "1234:1234"

volumes :
    mongo-data: